### ISSUE TITLE
Squash feature-task, merge feature-ability

### ISSUE THREAD

**Issue by nicholasjhenry** [civilcode/magasin-platform#24]
How about we squash a `feature-task` and merge `feature-abilities`. Thoughts?

https://blog.github.com/2016-04-01-squash-your-commits/

**Comment by frahugo** [comment]
@nicholasjhenry @bokay @tetiana12345678 

Alright.  I did some experiments in a dummy repo ([juice](https://github.com/civilcode/juice)).  Squashing is awesome!  I created a working branch, and then 2 sub-branches.  Master was at some point updated and needed to merged into the working branch.  No rebase at all.  When squashing, the merge commits are ignored (yes!).

Git keeps a trace of micro-commits in the individual branches, which is nice.  And in the master branch (or working branch), we end up with a squash commit with a reference to the pull request.  It is important to keep the line(s) with the references to the pull request.

![image](https://user-images.githubusercontent.com/14030/41293701-0acb01a2-6e24-11e8-88e4-7974ea09822e.png)

This is the squash commit for the working branch.  As you can see, we have links to the individual pull requests.  And if we view one of them, we can see all the micro commits, which is awesome.  And we do not have merge commits anymore in the master branch, another bonus.  But we end up with ONE commit for the working branch, which is probably not what we want since it would be better to see a commit for each task/chore.

So I did another experiment with a second working branch (`ability`).  The two tasks were squashed into `ability` and then the `ability` was merged into `master`, like we are used to do.  Now the master branch has commits for the tasks and a merge commit for the working branch.  So this is indeed the way to go I think.

It is kind of nice having just one commit for a feature in the master branch, especially when troubleshooting bugs.  We can easily revert to a commit prior to the feature and see if the bug was introduced by the feature.

As you can see, I'm all in with the squashing tasks/chores, and merging working branches when applicable.

**Comment by nicholasjhenry** [comment]
Excellent! Thank you for trialing this @frahugo

**Comment by frahugo** [comment]
Add to playbook.
